import type { Adventure } from "@/lib/db";

const FALLBACK_ADV_SERIES: Array<Pick<
  Adventure,
  "id" | "title" | "poster" | "description" | "base_setting" | "subsetting" | "tone" | "focus" | "world"
>> = [
  {
    id: "atomic-resort",
    title: "Atomic Resort",
    poster: "/adventures/AtomicResort.webp",
    description: "Ядерный курорт на краю мира и секреты, которые стоит раскрыть.",
    base_setting: "Фантастика",
    subsetting: "Твердая НФ",
    tone: "Серьезная атмосфера",
    focus: "Выживание",
    world: "Космос",
  },
  {
    id: "black-bell",
    title: "Black Bell",
    poster: "/adventures/BlackBell.webp",
    description: "Тревожный сигнал из глубины и тихие голоса в темноте.",
    base_setting: "Реализм",
    subsetting: "Современность",
    tone: "Мрачная атмосфера",
    focus: "Мистика",
    world: "Город парового солнца",
  },
  {
    id: "book-without-cover",
    title: "Book Without Cover",
    poster: "/adventures/BookWithoutCover.webp",
    description: "Книга без обложки открывает путь в забытые королевства.",
    base_setting: "Фентези",
    subsetting: "Эпическое фентези",
    tone: "Светлая атмосфера",
    focus: "Приключение",
    world: "DnD Миры",
  },
  {
    id: "curse-of-strahd",
    title: "Curse of Strahd",
    poster: "/adventures/CurseOfStrahd2.webp",
    description: "Проклятие замка оживает в ночи, и цена ошибки высока.",
    base_setting: "Фентези",
    subsetting: "Темное фентези",
    tone: "Мрачная атмосфера",
    focus: "Хоррор",
    world: "DnD Миры",
  },
  {
    id: "dead-loop",
    title: "Dead Loop",
    poster: "/adventures/DeadLoop.webp",
    description: "Цикл, который нельзя разорвать, и ответы между витками.",
    base_setting: "Фантастика",
    subsetting: "Мягкая НФ",
    tone: "Серьезная атмосфера",
    focus: "Детектив",
    world: "Будущее",
  },
  {
    id: "elf-dwarf-and-bad-idea",
    title: "Elf, Dwarf & a Bad Idea",
    poster: "/adventures/ElfDwarfAndBadIdea.webp",
    description: "Компания с характером и планы, которые явно пойдут наперекосяк.",
    base_setting: "Фентези",
    subsetting: "Сказочное фентези",
    tone: "Комедийная атмосфера",
    focus: "Комедия",
    world: "Средиземье",
  },
  {
    id: "jades-ashes",
    title: "Jade's Ashes",
    poster: "/adventures/JadesAshes.webp",
    description: "Пепел прошлого зовет в путь, где ставки выше дружбы.",
    base_setting: "Реализм + Фентези",
    subsetting: "Фольклор",
    tone: "Серьезная атмосфера",
    focus: "Драма",
    world: "История",
  },
  {
    id: "our-synthetic-paradise",
    title: "Our Synthetic Paradise",
    poster: "/adventures/OurSynteticParadise.webp",
    description: "Идеальный мир дает трещину, когда всплывает правда.",
    base_setting: "Фантастика",
    subsetting: "Киберпанк",
    tone: "Мрачная атмосфера",
    focus: "Катастрофа",
    world: "Будущее",
  },
  {
    id: "raven-stamp",
    title: "Raven Stamp",
    poster: "/adventures/RavenStamp.webp",
    description: "Письмо с печатью ворона ведет в опасное путешествие.",
    base_setting: "Реализм + Фентези",
    subsetting: "Историческое фентези",
    tone: "Светлая атмосфера",
    focus: "Приключение",
    world: "Вестерос",
  },
  {
    id: "shadow-above-waterdeep",
    title: "Shadow Above Waterdeep",
    poster: "/adventures/ShadowAboveWaterdeep.webp",
    description: "Тени сгущаются над городом, и герои должны раскрыть заговор.",
    base_setting: "Фентези",
    subsetting: "Городское фентези",
    tone: "Серьезная атмосфера",
    focus: "Детектив",
    world: "DnD Миры",
  },
  {
    id: "battle-of-helms-deep",
    title: "The Battle of Helm's Deep",
    poster: "/adventures/TheBattleofHelmsDeep.webp",
    description: "Крепость под осадой, и время на подготовку уходит.",
    base_setting: "Фентези",
    subsetting: "Эпическое фентези",
    tone: "Серьезная атмосфера",
    focus: "Военный",
    world: "Средиземье",
  },
  {
    id: "thin-blue-line",
    title: "Thin Blue Line",
    poster: "/adventures/ThinBlueLine2.webp",
    description: "Граница между порядком и хаосом тоньше, чем кажется.",
    base_setting: "Реализм",
    subsetting: "Современность",
    tone: "Серьезная атмосфера",
    focus: "Криминал",
    world: "Современность",
  },
];

export const fallbackAdventures: Adventure[] = FALLBACK_ADV_SERIES;

const fallbackIndex = new Map(fallbackAdventures.map((adventure) => [adventure.id, adventure]));

export function getFallbackAdventureById(id: string): Adventure | null {
  return fallbackIndex.get(id) ?? null;
}
