-- Справочник тегов: сюжетные маркеры и обстановка (не дублируют genres).
TRUNCATE tags CASCADE;

INSERT INTO tags (tag_id, tag_name) VALUES
  ('archaeology', 'Руины и артефакты'),
  ('assassination', 'Покушение и заговор'),
  ('conspiracy', 'Заговор'),
  ('cosmic-horror', 'Космический ужас'),
  ('curse', 'Проклятие'),
  ('dragons', 'Драконы'),
  ('dungeon', 'Подземелье'),
  ('escort', 'Эскорт'),
  ('espionage', 'Шпионаж'),
  ('festival', 'Праздник и торжество'),
  ('gold-rush', 'Золотая лихорадка'),
  ('gothic', 'Готика'),
  ('heist', 'Ограбление'),
  ('hired-work', 'Контракт и наём'),
  ('infiltration', 'Проникновение'),
  ('investigation', 'Расследование'),
  ('legal-drama', 'Суд и закон'),
  ('monster-hunt', 'Охота на монстра'),
  ('noir', 'Нуар'),
  ('ordeal', 'Ритуальное испытание'),
  ('pirates', 'Пираты'),
  ('race-against-time', 'Гонка со временем'),
  ('rescue', 'Спасение'),
  ('revolution', 'Революция'),
  ('robots', 'Роботы'),
  ('samurai', 'Самураи'),
  ('sea-voyage', 'Море'),
  ('siege-defense', 'Оборона'),
  ('space-station', 'Космическая станция'),
  ('time-loop', 'Временная петля'),
  ('undead', 'Нежить'),
  ('urban-intrigue', 'Городская интрига'),
  ('war-front', 'Война'),
  ('wasteland', 'Пустошь'),
  ('wilderness', 'Дикая местность'),
  ('witch-hunt', 'Охота на ведьм');
